namespace API_RMxControliD.Application.DTOs
{
    public class FuncionarioRHiDCadastrado
    {
        public bool excluded { get; set; }
        public int id { get; set; }
        //public string address { get; set; }
        //public bool admin { get; set; }
        //public string admissionDate { get; set; }
        public string admissionDateStr { get; set; }
        //public string age { get; set; }
        //public string applyAllGeofences { get; set; }
        //public string applyAllGeofencesStr { get; set; }
        //public string approvalFlow { get; set; }
        //public string approvalFlowName { get; set; }
        //public int? area { get; set; }
        //public string barcode { get; set; }
        //public int? cardCode { get; set; }
        //public string cardExibitType { get; set; }
        //public string cardTech { get; set; }
        //public string city { get; set; }
        //public string cnh { get; set; }
        //public string cnhCategoria { get; set; }
        //public string cnhVencimento { get; set; }
        //public string cnhVencimentoStr { get; set; }
        //public Int64? codigo { get; set; }
        //public string companyName { get; set; }
        //public string companyTradingName { get; set; }
        //public string costCenterName { get; set; }
        public string cpf { get; set; }
        //public string ctps { get; set; }
        //public string dateOfBirth { get; set; }
        //public string dateOfBirthStr { get; set; }
        public string dateShiftsStartStr { get; set; }
        //public string departmentName { get; set; }
        //public string dismissalDate { get; set; }
        //public string dismissalDateStr { get; set; }
        //public string district { get; set; }
        //public string email { get; set; }
        //public bool enableEmail { get; set; }
        //public bool expiredPassword { get; set; }
        //public string extension { get; set; }
        //public bool facialExcluded { get; set; }
        //public string facialFeedback { get; set; }
        //public int? facialTimestamp { get; set; }
        //public string fatherName { get; set; }
        //public int? forceFacialTimestamp { get; set; }
        //public string foto { get; set; }
        //public string fotoPontoObrigatoria { get; set; }
        //public string fotoPontoObrigatoriaStr { get; set; }
        //public string fotoPontoObrigatoriaWeb { get; set; }
        //public string fotoPontoObrigatoriaWebStr { get; set; }
        //public string gender { get; set; }
        //public bool genericShiftStartDateSelector { get; set; }
        //public string habilitaReconhecimentoFacial { get; set; }
        //public string habilitaReconhecimentoFacialStr { get; set; }
        //public string idApprovalFlow { get; set; }
        public int idCompany { get; set; }
        //public int? idCostCenter { get; set; }
        //public int? idCustomer { get; set; }
        //public int? idDepartment { get; set; }
        //public int? idPersonBoss { get; set; }
        public int idPersonProfile { get; set; }
        //public int? idPersonRole { get; set; }
        //public int? idReasonDismissal { get; set; }
        //public int? idShiftAtual { get; set; }
        //public int? idShifts { get; set; }
        //public int? id_funcionario { get; set; }
        //public string inicioBancoHoras { get; set; }
        //public string inicioBancoHorasStr { get; set; }
        //public string lastChange { get; set; }
        //public string listsDB { get; set; }
        //public string maritalStatus { get; set; }
        //public string menuAssinarPonto { get; set; }
        //public string menuAssinarPontoStr { get; set; }
        //public string menuComprovantes { get; set; }
        //public string menuComprovantesStr { get; set; }
        //public string menuEspelhoPonto { get; set; }
        //public string menuEspelhoPontoStr { get; set; }
        //public string menuHistorico { get; set; }
        //public string menuHistoricoStr { get; set; }
        //public string menuInformacoesGerais { get; set; }
        //public string menuInformacoesGeraisStr { get; set; }
        //public string menuPontoDiario { get; set; }
        //public string menuPontoDiarioStr { get; set; }
        //public string menuQuiosque { get; set; }
        //public string menuQuiosqueStr { get; set; }
        //public string menuSolicitacoes { get; set; }
        //public string menuSolicitacoesStr { get; set; }
        //public string menuVisualizarPonto { get; set; }
        //public string menuVisualizarPontoStr { get; set; }
        //public int? modoQuiosque { get; set; }
        //public string motherName { get; set; }
        public string name { get; set; }
        //public string nationality { get; set; }
        //public bool newEmployee { get; set; }
        public int? newIdShift { get; set; }
        //public string newPassword { get; set; }
        //public string numFolha { get; set; }
        //public string obs { get; set; }
        //public string operators { get; set; }
        //public int? password { get; set; }
        //public string permitirAcessoMobile { get; set; }
        //public string permitirAcessoMobileStr { get; set; }
        //public string permitirAlteracaoWeb { get; set; }
        //public string permitirAlteracaoWebStr { get; set; }
        //public string permitirMarcacaoAcessoFuncionario { get; set; }
        //public string permitirMarcacaoAcessoFuncionarioStr { get; set; }
        //public string permitirMarcacaoQuiosque { get; set; }
        //public string permitirMarcacaoQuiosqueStr { get; set; }
        //public string permitirMarcacaoWeb { get; set; }
        //public string permitirMarcacaoWebStr { get; set; }
        //public string personGeofences { get; set; }
        //public string personProfileName { get; set; }
        //public string personShifts { get; set; }
        //public string phone { get; set; }
        //public int? pin { get; set; }
        public long pis { get; set; }
        //public string placeOfBirth { get; set; }
        //public string qrCodeInfo { get; set; }
        //public string reasonDismissalName { get; set; }
        public string registration { get; set; }
        //public int? rfid { get; set; }
        //public string rfidString { get; set; }
        //public string rfidStringCsv { get; set; }
        //public string rg { get; set; }
        //public string roleName { get; set; }
        //public int? saldoBancoHoras { get; set; }
        //public string selectedGeofencesId { get; set; }
        //public string senhaAcessoWeb { get; set; }
        //public string shiftAtualName { get; set; }
        //public string shifts { get; set; }
        //public string socialName { get; set; }
        //public string state { get; set; }
        //public int? status { get; set; }
        //public string statusStr { get; set; }
        //public string templateArray { get; set; }
        //public string templates { get; set; }
        //public string timeZone { get; set; }
        //public string timeZoneStr { get; set; }
        //public string useGeofencing { get; set; }
        //public string useGeofencingStr { get; set; }
        //public string userLocale { get; set; }
        //public int? viaCracha { get; set; }
        //public string zip { get; set; }

    }
}
